### ISSUE TITLE
some of the links in index.html don't work

### ISSUE THREAD

**Issue by kevinb7** [csvoss/csvoss.github.io#1]
```<a href="SPARC">http://sparc-camp.org/</a>``` should probably be ```<a href="http://sparc-camp.org/">SPARC</a>```.  Also the links to "Projects" and "Blogs" don't go anywhere.  Probably best to make them disable until there's something to link to.

**Comment by csvoss** [comment]
Oh hi! I haven't been looking at my GitHub notifications very frequently...

Thanks -- this should be fixed now!

**Comment by kevinb7** [comment]
Looks good :+1:
